import Head from "next/head"
import ProductCard from "@/components/product/ProductCard"
import { GetServerSideProps } from "next"
import { prisma } from "@/lib/prisma"
import { useState } from "react"
import { getServerSession } from "next-auth"
import { authOptions } from "./api/auth/[...nextauth]"
import Layout from "@/components/layout"
import { ReactElement } from "react"

interface Product {
  products: {
    id: string
    name: string
    price: number
    imageUrl: string
    categoryId: string
    createdAt: string
  }[]
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const productsArray = await prisma.product.findMany()
  const products = JSON.parse(JSON.stringify(productsArray))

  const session = await getServerSession(context.req, context.res, authOptions)
  if (session?.user === undefined) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    }
  }

  return {
    props: { products },
  }
}

export default function Home({ products }: Product) {
  const [filteredProducts, setFilteredProducts] = useState(products)

  const filterProductsByCategory = (category: string) => {
    const newProducts = products.filter((prod) => prod.categoryId === category)

    setFilteredProducts(newProducts)
  }

  return (
    <>
      <Head>
        <title>Booze - Bebidas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/booze.svg" />
      </Head>
      <main className="flex flex-col items-start justify-center gap-8 py-8 px-4">
        <h1 className="text-3xl font-bold text-red-600">Bem vindo, Boozer</h1>

        <div className="flex flex-wrap items-start justify-start w-full py-8 gap-4">
          <div
            className="border border-red-500 text-red-500 hover:text-red-700 rounded-md px-5 py-2 font-semibold cursor-pointer transition-all"
            onClick={() => setFilteredProducts(products)}
          >
            Todos
          </div>
          <div
            className="border border-red-500 text-red-500 hover:text-red-700 rounded-md px-5 py-2 font-semibold cursor-pointer transition-all"
            onClick={() =>
              filterProductsByCategory("ec049b03-8048-4c21-9680-4dc15ad86ac4")
            }
          >
            Cervejas
          </div>
          <div
            className="border border-red-500 text-red-500 hover:text-red-700 rounded-md px-5 py-2 font-semibold cursor-pointer transition-all"
            onClick={() =>
              filterProductsByCategory("d61bd50c-35fc-49c3-916d-00096a00220e")
            }
          >
            Refrigerantes
          </div>
          <div
            className="border border-red-500 text-red-500 hover:text-red-700 rounded-md px-5 py-2 font-semibold cursor-pointer transition-all"
            onClick={() =>
              filterProductsByCategory("4e36fcc7-b775-4c65-8971-7f09f0ca42d0")
            }
          >
            Combos
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 m-auto w-full">
          {filteredProducts.map((product) => {
            return <ProductCard key={product.id} {...product} />
          })}
        </div>
      </main>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}
