import Head from 'next/head'
import { Inter } from 'next/font/google'
import ProductCard from '@/components/product/ProductCard'
import { GetServerSideProps } from 'next'
import { prisma } from '@/lib/prisma'

const inter = Inter({ subsets: ['latin'] })

interface Product {
  products: {
    id: number
    name: string
    price: number
    imageUrl: string
  }[]
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const productsArray = await prisma.product.findMany()
  const products = JSON.parse(JSON.stringify(productsArray))

  return {
    props: { products },
  }
}

export default function Home({ products }: Product) {
  console.log(products)
  return (
    <>
      <Head>
        <title>Booze - Bebidas</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/minibar-black.png' />
      </Head>
      <main className='flex flex-col items-start justify-center gap-8 py-8 px-4'>
        <h1 className='text-2xl font-bold text-center w-full'>Hello Boozer</h1>

        <div className='flex items-center justify-between w-full py-8'>
          <div className='bg-slate-600 rounded-md p-5 font-semibold hover:bg-slate-700 cursor-pointer transition-all'>
            Cervejas
          </div>
          <div className='bg-slate-600 rounded-md p-5 font-semibold hover:bg-slate-700 cursor-pointer transition-all'>
            Refrigerantes
          </div>
          <div className='bg-slate-600 rounded-md p-5 font-semibold hover:bg-slate-700 cursor-pointer transition-all'>
            Combos
          </div>
        </div>

        <div className='grid grid-cols-1 md:grid-cols-3 gap-4 m-auto w-full'>
          {products.map((product) => {
            return <ProductCard key={product.id} {...product} />
          })}
        </div>
      </main>
    </>
  )
}
